version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mapeia a pasta local automaticamente (funciona em Windows, Mac e Linux)
      - ./data:/app/data
    # O comando abaixo roda a migration do Alembic ANTES de ligar a API
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
